name = "kiss-worker" main = "src/index.js" compatibility_date = "2023-07-28" kv_namespaces = [ { binding = "KV", id = "045b8382f463439786288c1d943e2e4c", preview_id = "01d3a47d26ca4732b4e6189b4d095ffe" }
